### ISSUE TITLE
DXL Finish Objective Not working.

### ISSUE THREAD

**Issue by assersson** [PikaMug/DungeonsXLQuestsModule#1]
I have made an quest with custom objective (DXL Finish Objective). Players need to complete a Dungeon called Hidden Threat, and they will get their reward then. But seems like im getting an error messages to the console when Dungeon is finished. Quests Journal shows that Quest is still on going even it should be completed. Heres the errors that pops up in the console:

[ERROR] Could not pass event DGamePlayerRewardEvent to Quests v3.9.2-b94

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at de.erethon.dungeonsxl.player.DGamePlayer.leave(DGamePlayer.java:394) ~[?:?]

at de.erethon.dungeonsxl.player.DGroup.lambda$finish$2(DGroup.java:596) ~[?:?]

at de.erethon.dungeonsxl.player.DGroup$$Lambda$5123.00000000738DEBE0.accept(Unknown Source) ~[?:?]

at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_212]

at de.erethon.dungeonsxl.player.DGroup.finish(DGroup.java:596) ~[?:?]

at de.erethon.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:588) ~[?:?]

at de.erethon.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:573) ~[?:?]

at de.erethon.dungeonsxl.player.DGamePlayer.finishFloor(DGamePlayer.java:542) ~[?:?]

at de.erethon.dungeonsxl.sign.button.EndSign.push(EndSign.java:127) ~[?:?]

at de.erethon.dungeonsxl.api.sign.Button.trigger(Button.java:73) ~[?:?]

at de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:188) ~[?:?]

at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]

at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]

at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:72) ~[?:?]

at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$3909.000000008404F590.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoClassDefFoundError: de.erethon.dungeonsxl.reward.Reward

at me.pikamug.DungeonsXLQuests.DungeonsXLMoneyRewardObjective.onDGamePlayerFinish(DungeonsXLMoneyRewardObjective.java:40) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

... 41 more

Caused by: java.lang.ClassNotFoundException: de.erethon.dungeonsxl.reward.Reward

at java.net.URLClassLoader.findClass(URLClassLoader.java:591) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]

at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:1124) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]

at me.pikamug.DungeonsXLQuests.DungeonsXLMoneyRewardObjective.onDGamePlayerFinish(DungeonsXLMoneyRewardObjective.java:40) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

... 41 more

[ERROR] Could not pass event DGamePlayerFinishEvent to Quests v3.9.2-b94

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at de.erethon.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:597) ~[?:?]

at de.erethon.dungeonsxl.player.DGamePlayer.finish(DGamePlayer.java:573) ~[?:?]

at de.erethon.dungeonsxl.player.DGamePlayer.finishFloor(DGamePlayer.java:542) ~[?:?]

at de.erethon.dungeonsxl.sign.button.EndSign.push(EndSign.java:127) ~[?:?]

at de.erethon.dungeonsxl.api.sign.Button.trigger(Button.java:73) ~[?:?]

at de.erethon.dungeonsxl.api.sign.DungeonSign.updateTriggers(DungeonSign.java:188) ~[?:?]

at de.erethon.dungeonsxl.trigger.Trigger.updateDSigns(Trigger.java:109) ~[?:?]

at de.erethon.dungeonsxl.trigger.InteractTrigger.onTrigger(InteractTrigger.java:50) ~[?:?]

at de.erethon.dungeonsxl.sign.DSignListener.onPlayerInteract(DSignListener.java:72) ~[?:?]

at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:442) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1251) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$3909.000000008404F590.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.NoSuchMethodError: de/erethon/dungeonsxl/player/DGamePlayer.getDGroup()Lde/erethon/dungeonsxl/player/DGroup; (loaded from file:/home/gs-41575/plugins/dungeonsxl-dist-0.18-SNAPSHOT-905.jar by org.bukkit.plugin.java.PluginClassLoader@668d84dd) called from class me.pikamug.DungeonsXLQuests.DungeonsXLFinishObjective (loaded from jar:file:plugins/Quests/modules/DungeonsXLQuestsModule-1.1.jar!/ by java.net.FactoryURLClassLoader@172292dc).

at me.pikamug.DungeonsXLQuests.DungeonsXLFinishObjective.onDGamePlayerFinish(DungeonsXLFinishObjective.java:35) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-ce66f69]

... 36 more

**Comment by PikaMug** [comment]
Thanks for the report. See https://github.com/PikaMug/Quests/issues/1188
